### ISSUE TITLE
Problem loading property file for Arjuna specific extensions

### ISSUE THREAD

**Issue by nmcl** [nmcl/wfswarm-example-arjuna-old#1]
Until the example is finished, the hidden URL to test the Arjuna specific stuff is /aa

Trying with ...

java -jar ./target/wildfly-swarm-example-transactions-1.0.0.Beta1-SNAPSHOT-swarm.jar

and then the URL ...

http://localhost:8080/aa

... in the console produces the following error on the console (we catch it in the code to display it more easily):

2015-12-24 15:09:21,306 ERROR [stderr] (default task-1) Caused by: java.lang.RuntimeException: unable to load properties from jar:file:/var/folders/0x/khpgbspj3h57mc2ln9mdnd_00000gn/T/org.jboss.narayana.jts:narayana-jts-idlj:5.2.9.Final486764271646177045.jar!/jbossts-properties.xml
2015-12-24 15:09:21,307 ERROR [stderr] (default task-1) 	at com.arjuna.common.util.propertyservice.AbstractPropertiesFactory.getPropertiesFromFile(AbstractPropertiesFactory.java:107)
2015-12-24 15:09:21,307 ERROR [stderr] (default task-1) 	at com.arjuna.common.util.propertyservice.AbstractPropertiesFactory.initDefaultProperties(AbstractPropertiesFactory.java:195)
2015-12-24 15:09:21,307 ERROR [stderr] (default task-1) 	at com.arjuna.common.util.propertyservice.AbstractPropertiesFactory.getDefaultProperties(AbstractPropertiesFactory.java:62)

Full details here ...

https://gist.github.com/nmcl/2afaf92e17439b0c0556

Now it's fairly obvious that the property file (jabots-properties.xml) is located and loaded by Narayana within normal JTA/JTS operations of WildFly or even WildFly-Swarm (see the Swarm war transactions example). So I'm not sure what's going on here yet.

I had seen a similar issue a year ago when porting Narayana to run with Avian and it was an issue within Narayana (https://issues.jboss.org/browse/JBTM-2236). However, since the property file is being loaded by WildFly, as mentioned above, I'm not sure this is the issue.

**Comment by nmcl** [comment]
com.arjuna.common.util.propertyservice.ArjunaPropertiesFactory is used to locate the property file. You can always provide your own at runtime rather than use the one within WildFly and hence not the one in the Swarm jar. One way of doing this is via the com.arjuna.ats.arjuna.common.propertiesFile System property at runtime. So I added the exact same property file from the jar into the example (in the etc directory) and used the following command:

java -Dcom.arjuna.ats.arjuna.common.propertiesFile=/Users/marklittle/github/wfswarm-example-arjuna/etc/jbossts-properties.xml -jar ./target/wildfly-swarm-example-arjuna-1.0.0.Beta1-SNAPSHOT-swarm.jar

Now before we do this let's make sure the WildFly (Swarm) example is going to use this, so we'll deliberately give a broken link for the file:

java -Dcom.arjuna.ats.arjuna.common.propertiesFile=/Users/marklittle/github/wfswarm-example-arjuna/etc/jbossts-propert.xml

And we get https://gist.github.com/nmcl/cbb4026d80582505e7f4

So we're ok to assume that if we use a valid file location and name, something different will happen :)

This time we use ...

java -Dcom.arjuna.ats.arjuna.common.propertiesFile=/Users/marklittle/github/wfswarm-example-arjuna/etc/jbossts-properties.xml -jar ./target/wildfly-swarm-example-arjuna-1.0.0.Beta1-SNAPSHOT-swarm.jar

... and when the system is started correctly we use the same url as before ...

http://localhost:8080/aa

... and it fails again! This time with ...

2015-12-24 15:21:55,178 ERROR [stderr] (default task-1) Caused by: java.lang.RuntimeException: unable to load properties from /Users/marklittle/github/wfswarm-example-arjuna/etc/jbossts-properties.xml

Full trace is located at https://gist.github.com/nmcl/548cec4505965e33c10d

So WildFly(Swarm) is able to locate this new property file during setup of JTA/JTA but not when the JAX-RS example is trying to do so.

**Comment by nmcl** [comment]
So the Arjuna-like example for WildFly in the Narayana repo (https://github.com/jbosstm/quickstart/tree/master/wildfly/setCheckedActionFactoryExample) works fine in WildFly 9.0.2.Final ...

https://gist.github.com/nmcl/03fe9abb6a8197ddca5c

The example does require the fix I mentioned here (https://issues.jboss.org/browse/JBTM-2591) though. But regardless, this does show that WildFly is able to access the Arjuna specific APIs and classes.

**Comment by bobmcwhirter** [comment]
I'll look deeper. Next year. Happy Christmas!

**Comment by nmcl** [comment]
Ah, don't worry about the timing :) Just taking the opportunity to have some fun. Have a great Christmas and new year too! (I hear you're married now?)

**Comment by nmcl** [comment]
As a war the example works fine ...

https://gist.github.com/nmcl/7bdf56c84bea6ea48ddc

**Comment by nmcl** [comment]
I've refactored the example into war and jar directories. The jar directory illustrates the problem, allowing me to make some progress with using a war.

**Comment by bobmcwhirter** [comment]
Feel free to work directly in the example repo or a fork thereof.

**Comment by nmcl** [comment]
Seems like later versions of Swarm fix whatever caused the problem ...

https://issues.jboss.org/browse/SWARM-241
